// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.DBContext;

#nullable disable

namespace School.Migrations
{
    [DbContext(typeof(SchoolInfoDbContext))]
    partial class SchoolInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.DTO.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("School.Models.SchoolInfo", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"));

                    b.Property<long>("HeadMaster_MobilNO")
                        .HasColumnType("bigint");

                    b.Property<int>("How_Many_Teachers_Gender_Female")
                        .HasColumnType("int");

                    b.Property<int>("How_Many_Teachers_Gender_Male")
                        .HasColumnType("int");

                    b.Property<string>("SchoolLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School_Admin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Teachers")
                        .HasColumnType("int");

                    b.HasKey("SchoolId");

                    b.ToTable("SchoolInfo");
                });

            modelBuilder.Entity("School.Models.TeachersInformation", b =>
                {
                    b.Property<int>("TeachersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeachersId"));

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Joining_Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staying_Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeachersAge")
                        .HasColumnType("int");

                    b.Property<string>("TeachersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Teachers_MobileNo")
                        .HasColumnType("bigint");

                    b.Property<float>("Teachers_salary")
                        .HasColumnType("real");

                    b.Property<string>("currently_workking_school_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("which_Class_Teaching")
                        .HasColumnType("int");

                    b.HasKey("TeachersId");

                    b.ToTable("TeachersInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
